### ISSUE TITLE
How to Define Shared and Task-Specific Parameters in the PLE Framework

### ISSUE THREAD

**Issue by zelota556** [EnnengYang/AdaTask#1]
Thank you for sharing your very meaningful work and sharing your codes on this repository. I have a question regarding **parameter definition about the PLE framework** when using AdaTask.

Could you please provide guidance or examples on how to:
1.    Define shared parameters that are used across all tasks (just shared experts?).
2.    Define task-specific parameters that are unique to each task (task-specific experts and towers?).

I really appreciate your help!!!

**Comment by EnnengYang** [comment]
Hi,
Thank you very much for your interest in our work!

The goal of AdaTask is to balance the dominance of "shared parameters" (i.e., parameters common to both tasks), so shared parameters in PLE (as an example in the figure below) should include: embedding/input layer, shared experts across layers (blue in the figure below), and shared gating (blue in the figure below) across layers. All red and green modules are task-private modules.

You can try this to see if it works. Thank you.

<img width="220" alt="PLE" src="https://github.com/EnnengYang/AdaTask/assets/19388092/4ad016fc-55d2-4fcf-8932-84bd562cc968">

**Comment by zelota556** [comment]
Thank you for your detailed explanation and for clarifying the concept of shared parameters in AdaTask. I am very grateful to you for providing this example, I have understood it and I really feel your help.
